#! /bin/sh

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         2
bspc config window_gap          5 #12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# RESOLUCION ARANDR


# WALLPAPER

# Pongo un fondo de pantalla aleatorio con el archivo que yo creé
~/.config/bin/change_wallpaper.sh

#feh --bg-fill ~/Wallpaper/s4vitar.png   # Por defecto, fondo de pantalla de s4vitar

# POLYBAR
~/.config/polybar/my_launch.sh

# CUSTOM
bspc config focus_follows_pointer true

# PICOM
#picom &   # BIFUZ -> MI configuracion linea de abajo
picom --experimental-backends &
bspc config border_width 0

xsetroot -cursor_name left_ptr &

bpsc 
